

ALTER TABLE DODATKOWY_CUSTOM
ADD CONSTRAINT FK_PRACOWNIK_DODATKOWY_CUSTOM
FOREIGN KEY (PESEL_PR)
REFERENCES PRACOWNIK(PESEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT FK_PRACOWNIK_ZAMOWIENIE
FOREIGN KEY (PESEL_PR)
REFERENCES PRACOWNIK(PESEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT FK_KLIENT_ZAMOWIENIE
FOREIGN KEY (PESEL_KL)
REFERENCES KLIENT(PESEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE SAMOCHODY
ADD CONSTRAINT FK_DODATKOWY_CUSTOM_SAMOCHODY
FOREIGN KEY (CUSTORDER_ID)
REFERENCES DODATKOWY_CUSTOM(CUSTORDER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT FK_SAMOCHODY_ZAMOWIENIE
FOREIGN KEY (VEHICLE_ID)
REFERENCES SAMOCHODY(VEHICLE_ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE TEST_DRIVES
ADD CONSTRAINT FK_KLIENT_TEST_DRIVES
FOREIGN KEY (PESEL_KL)
REFERENCES KLIENT(PESEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE TEST_DRIVES
ADD CONSTRAINT FK_PRACOWNIK_TEST_DRIVES
FOREIGN KEY (PESEL_PR)
REFERENCES PRACOWNIK(PESEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE TEST_DRIVES
ADD CONSTRAINT FK_SAMOCHODY_TEST_DRIVES
FOREIGN KEY (VEHICLE_ID)
REFERENCES SAMOCHODY(VEHICLE_ID)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE TEST_DRIVES
ADD CONSTRAINT FK_OPINIE_TEST_DRIVES
FOREIGN KEY (OPINIE_ID)
REFERENCES OPINIE(OPINIE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PLATNOSCI
ADD CONSTRAINT FK_ZAMOWIENIE_PLATNOSCI
FOREIGN KEY (ORDER_ID)
REFERENCES ZAMOWIENIE(ORDER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;


ALTER TABLE PERSONALIZACJA
ADD CONSTRAINT FK_DODATKOWY_CUSTOM_PERSONALIZACJA
FOREIGN KEY (CUSTORDER_ID)
REFERENCES DODATKOWY_CUSTOM(CUSTORDER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE AKCESORIUM
ADD CONSTRAINT FK_DODATKOWY_CUSTOM_AKCESORIUM
FOREIGN KEY (CUSTORDER_ID)
REFERENCES DODATKOWY_CUSTOM(CUSTORDER_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PAKIET
ADD CONSTRAINT FK_MODEL_PAKIET
FOREIGN KEY (MODEL)
REFERENCES STATIC_MODEL(MODEL)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE SAMOCHODY
ADD CONSTRAINT FK_PAKIET_SAMOCHODY
FOREIGN KEY (NAZWA_PAK)
REFERENCES PAKIET(NAZWA)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT FK_OPINIE_ZAMOWIENIE
FOREIGN KEY (OPINIE_ID)
REFERENCES OPINIE(OPINIE_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE PRACOWNIK
ADD CONSTRAINT FK_STANOWISKO_PRACOWNIK
FOREIGN KEY (STANOWISKO_TYPE)
REFERENCES STATIC_STANOWISKO(STANOWISKO_TYPE)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE OPINIE
ADD CONSTRAINT FK_OPINIE_OPINIE
FOREIGN KEY (OPINIE_TYPE)
REFERENCES STATIC_OPINIE(OPINIE_TYPE)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE ZAMOWIENIE
ADD CONSTRAINT FK_STATUS_ZAMOWIENIE
FOREIGN KEY (STATUS_TYPE)
REFERENCES STATIC_STATUS(STATUS_TYPE)
ON UPDATE CASCADE
ON DELETE CASCADE;



SELECT* FROM PRACOWNIK WHERE PESEL='67890123455';
SELECT* FROM ZAMOWIENIE WHERE PESEL_PR='67890123455';
update PRACOWNIK SET PESEL='11223344556' WHERE PESEL='67890123455'
SELECT* FROM PRACOWNIK WHERE PESEL='11223344556';
SELECT* FROM ZAMOWIENIE WHERE PESEL_PR='11223344556';



SELECT* FROM KLIENT;
SELECT* FROM KLIENT WHERE IMIE='MARCIN';
SELECT* FROM ZAMOWIENIE WHERE PESEL_KL='99123456789';
SELECT* FROM TEST_DRIVES WHERE PESEL_KL='99123456789';
SELECT* FROM OPINIE WHERE OPINIE_ID='19';

SELECT* FROM TEST_DRIVES WHERE OPINIE_ID='19';
update KLIENT SET PESEL='1', IMIE='LIONEL' WHERE PESEL='22833712341';


SELECT* FROM SAMOCHODY WHERE VEHICLE_ID='19';
UPDATE SAMOCHODY SET NAZWA_PAK='Economy GOLF', MODEL='GOLF' WHERE VEHICLE_ID='19';

SELECT* FROM ZAMOWIENIE WHERE VEHICLE_ID='19';
SELECT* FROM KLIENT WHERE PESEL='90123456789';