DROP TABLE IF EXISTS TEST_DRIVES;
DROP TABLE IF EXISTS PLATNOSCI;
DROP TABLE IF EXISTS ZAMOWIENIE;
DROP TABLE IF EXISTS KLIENT;
DROP TABLE IF EXISTS SAMOCHODY;
DROP TABLE IF EXISTS OPINIE;
DROP TABLE IF EXISTS PAKIET;
DROP TABLE IF EXISTS AKCESORIUM;
DROP TABLE IF EXISTS PERSONALIZACJA;
DROP TABLE IF EXISTS DODATKOWY_CUSTOM;
DROP TABLE IF EXISTS PRACOWNIK;
DROP TABLE IF EXISTS STATIC_STANOWISKO;
DROP TABLE IF EXISTS STATIC_OPINIE;
DROP TABLE IF EXISTS STATIC_STATUS;
DROP TABLE IF EXISTS STATIC_MODEL;

